### ISSUE TITLE
Test not passing due to problem with in-Python HTTPS requests in test suite

### ISSUE THREAD

**Issue by guillochon** [conda-forge/mosfit-feedstock#23]
@conda-forge-admin @conda-forge-coordinator It appears that #22 is failing because the build cannot access the internet for its tests. This problem is pretty new, past couple days. Any idea what's going on?

**Comment by jakirkham** [comment]
FYI those are bots.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by scopatz** [comment]
I have noticed something similar on some of my feedstocks and it is related to ssl/tls trying and failing to verify certificates. I got around this by setting my downloads to be not verify, even though they are using https

**Comment by patricksnape** [comment]
I also had this on the OpenCV builds I just did - ended up switching to requests and installing certifi which fixed things.

**Comment by jakirkham** [comment]
Might be related to issue ( https://github.com/conda/conda-build/issues/2255 ). Think this could be caused by PR ( https://github.com/conda/conda-build/pull/2142 ), which was backported to `conda-build` 2.1 in commit ( https://github.com/conda/conda-build/commit/1ea628795536dce848d26adaff6db02585afd483 ). Could try unsetting `REQUESTS_CA_BUNDLE` and `SSL_CERT_FILE` in the build to fix it. If that works, we might want to patch `conda-build`.

**Comment by pkgw** [comment]
Local Docker testing indicates that the tests do indeed start passing if those variables are unset in the `forge_test.sh` script.

**Comment by pkgw** [comment]
For reference, here's the stack trace from the bit of code that surfaces the problem in this particular case:

```
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/site-packages/mosfit/__main__.py", line 5, in <module>
    main.main()
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/site-packages/mosfit/main.py", line 847, in main
    Fitter(**fitargs).fit_events(**fitargs)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/site-packages/mosfit/fitter.py", line 268, in fit_events
    event_list, offline=self._offline)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/site-packages/mosfit/fetcher.py", line 96, in fetch
    timeout=10)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/site-packages/mosfit/utils.py", line 32, in get_url_file_handle
    return urlopen(url, timeout=timeout)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/feedstock_root/build_artefacts/mosfit_1512409210715/_t_env/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
```

**Comment by jakirkham** [comment]
Thanks for taking a closer look, @pkgw. Then I think the next course of action is to figure out how to patch `conda-build` to fix this issue.

**Comment by guillochon** [comment]
@pkgw's commit (https://github.com/guillochon/mosfit-feedstock/commit/7a3a9ca4236f7aa6e722d5b14dcb18b99f3de503) fixed the issue in the feedstock, so this does appear to be the problem.

**Comment by jakirkham** [comment]
Another thing that would be good to check is what these variables are set to before we unset them.

**Comment by pkgw** [comment]
@jakirkham I checked. They were empty.

**Comment by jakirkham** [comment]
Thanks for checking. Have noted what you found upstream. Expect this should be a rather simple patch to `conda-build`.
